require "plugins"
require "keymaps"
require "options"
require "nvim-tree-config"
-- require "bufferline-config"
require "cmp-config"
require "mason-config"
require "lsp-config"
require "telescope-config"
require "catppuccin-config"
require "comment-config"
require "lualine-config"
require "toggleterm-config"
require "harpoon-config"
-- require "tokyonight-config"
--  from my
-- require "nvim-autopairs"
