require "keymaps"
require "plugins"
require "options"
require "nvim-tree-config"
-- require "bufferline-config"
require "cmp-config"
require "mason-config"
require "lsp-config"
require "telescope-config"
require "catppuccin-config"
require "comment-config"
require "lualine-config"
require "toggleterm-config"
require "harpoon-config"
require "treesitter-config"
-- require "tokyonight-config"
-- require "null-ls-config"
-- require "prettier-config"
require "gitsigns-config"
-- require "nvim-autopairs"
